export 'forgot_page.dart';
export 'login_page.dart';
export 'register_page.dart';
export 'reset_page.dart';
export 'code_otp_page.dart';
export 'new_password_page.dart';
export 'document_page.dart';
export 'choise_register_page.dart';
export 'create_pin_page.dart';